### ISSUE TITLE
style 展示逻辑存在问题

### ISSUE THREAD

**Issue by SzHeJason** [NervJS/nerv#103]
当将 inLineStyle 设置为 空对象 style 属性并没有发生变化
[![Edit Nerv sandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/92187wz6zo)

**Comment by yuche** [comment]
https://codesandbox.io/s/1qxjr8ry6l

升级一些你的 nervjs 应该就可以了
