### ISSUE TITLE
[nerv-test-utils] 1.4.beta.5 hooks can only be called in a stateless component

### ISSUE THREAD

**Issue by ZhangJian-3ti** [NervJS/nerv#126]
如果用functional的方式，则jest test会报
invalid hooks call: hooks can only be called in a stateless component.

**Comment by yuche** [comment]
能做一个简单的复现吗

**Comment by ZhangJian-3ti** [comment]
用 jest 跑的，怎么建立复现？

**Comment by yuche** [comment]
开一个新仓库，提交到 github

**Comment by ZhangJian-3ti** [comment]
OK,我再测试下。

**Comment by ZhangJian-3ti** [comment]
Fixed in https://github.com/NervJS/nerv/commit/420319d24e38d12d5116856fc9f16ca7de4bfb09
