### ISSUE TITLE
If this is identical to React 16 why not contribute it to the project?

### ISSUE THREAD

**Issue by igorgue** [NervJS/nerv#13]
In other words... why is everyone wasting their time reinventing the wheel so what people just want to be famous? Is this another China "Me too" moment?

**Comment by drcmda** [comment]
There are hardwired requirements into React that you couldn't remove and that wouldn't be accepted. Dan Abramov spoke about it once. The official way is by using the reconciler, but it can only take on filling the target, and the size difference has a hard limit starting from anything over 13kb.

<img width="599" alt="screen shot 2018-01-10 at 22 41 28" src="https://user-images.githubusercontent.com/2223602/34796920-8103d1d6-f657-11e7-8376-e9778a0266f9.png">

I think this is how it should be done: a true drop in replacement without altering the api like inferno and preact did. Develop in React, alias to this in prod, it wouldn't hurt or fragment React.

**Comment by luckyadam** [comment]
@igorgue  Maybe this discussion can unlock your doubts #10
