### ISSUE TITLE
Run test with Jest 24, throws ReactIs.isElement is not a function

### ISSUE THREAD

**Issue by ZhangJian-3ti** [NervJS/nerv#130]
Latest  Nervjs 1.4.0 with nerv-test-utils.

Any idea to resolve this? Thanks.

**Comment by yuche** [comment]
Use Jest 23 instead.

**Comment by ZhangJian-3ti** [comment]
@yuche Thank you very much for your quick response. 
I used use the Jest 23, but since it's missing some functionalities which I need for now( such as resolveSnapshotPath... ), so I have to switch to Jest 24.

**Comment by ZhangJian-3ti** [comment]
partly resolved 
https://github.com/NervJS/nerv/commit/9fe346b762e3f26780fd17586d7cfadb0f405604

**Comment by bsdfzzzy** [comment]
@ZhangJian-3ti Hello, did you config nerv-is into moduleNameMapper? I encountered the same problem.
