### ISSUE TITLE
兼容 React 生态系统？

### ISSUE THREAD

**Issue by guxingke201** [NervJS/nerv#134]
[Nerv 提供了比 React 更好的浏览器兼容性和更高的性能，与此同时也不会放弃 React 庞大的生态系统。兼容 React 生态系统是我们开发 Nerv 的重要目标之一。](https://nervjs.github.io/docs/guides/switching-to-nerv.html)
试过几个脚手架，只是改了别名，都不能用。构建正常，运行报异常。做这个实验的目的是想用taro-ui，可惜的是，连nervjs这关都过不来

![image](https://user-images.githubusercontent.com/8326941/60417834-ffb6ea00-9c13-11e9-8d92-e539403bdbc0.png)

**Comment by yuche** [comment]
你出现这个错误说明配置有误，创建 taro-ui 组件的 nerv 引用和你主应用的 nerv 不是同一个 nerv。如果 nerv 连 taro ui 都跑不了，那你在 taro ui 的就不能预览组件了。

**Comment by guxingke201** [comment]
还没有用taro-ui，只是用了别名替换，把react和react-dom替换成nervjs

**Comment by yuche** [comment]
请问你用的哪个脚手架，是怎么设置的 alias？

**Comment by guxingke201** [comment]
公司内部的脚手架，有三个，分别报不同的异常。我试试用react-create-app整理一个可以重现demo给你

**Comment by guxingke201** [comment]
先来一个简单的，切换到react-route-5分支，nervjs和react-route5一起用有点问题

https://github.com/guxingke201/react-to-nervjs/tree/react-route-5

**Comment by yuche** [comment]
`Route` 要用 `Switch` 包起来。
如果你用 react-router@4 的话就没这个限制，react-router@5 Route 的机制有一些变化，需要框架可以处理数组类型的组件，但是 Nerv 还不支持 fragment，所以跑不了。

**Comment by guxingke201** [comment]
切换到gmc分支，react没问题，nervjs报异常
https://github.com/guxingke201/react-to-nervjs/tree/gmc

**Comment by guxingke201** [comment]
公司内部三代脚手架，一代和二代先不整理了，有需要可以再整理出来

**Comment by yuche** [comment]
Routes 的组件很难判断里面干了什么，如果能有源码的话比较方便 debug。

**Comment by guxingke201** [comment]
https://github.com/gem-mine/durex-router

**Comment by guxingke201** [comment]
@yuche 对比了react和nervjs，发现nervjs是从state.value里拿数据，react不是，这个能改吗？
![image](https://user-images.githubusercontent.com/8326941/61437495-cf8b7d00-a96f-11e9-9914-ff3e4c3e9b1c.png)

**Comment by yuche** [comment]
> state

这样在什么样的情况下会造成无法工作？

**Comment by guxingke201** [comment]
感觉和[这里的代码](https://github.com/gem-mine/durex/blob/master/src/render.js)有关系，我问问开发这个组件的同事

![image](https://user-images.githubusercontent.com/8326941/61439460-2a26d800-a974-11e9-9c5e-c513a06d1989.png)

**Comment by guxingke201** [comment]
问过了，同事那边的定位说没有关系，初步定位和react-router有关系

**Comment by guxingke201** [comment]
同事那边没找到原因，但是把react-router升级到5就解决了

**Comment by guxingke201** [comment]
没有解决，出现其他异常：

![image](https://user-images.githubusercontent.com/8326941/61608591-d5da6b80-ac85-11e9-8171-061d0bad9301.png)

**Comment by guxingke201** [comment]
@yuche 请看这个分支，nerv使用connected-react-router@6x和react-loadable报异常，单独使用connected-react-router@6x不会报异常
https://github.com/guxingke201/react-to-nervjs/tree/connected-react-router-6x

**Comment by guxingke201** [comment]
换了一个思路，用react替换掉taro-ui里nerv，并处理了taro-ui里style样式不兼容react语法的问题，再从@tarojs/webpack-runner挖些配置出来，最终实现taro-ui可以成功运行在react脚手架里

**Comment by ssttii** [comment]
把react-router升级到5,ie8下能正常工作吗
