### ISSUE TITLE
中文文档 链接 失效(CN document Link failed)

### ISSUE THREAD

**Issue by Maple13** [NervJS/nerv#15]
CN document Link failed

**Comment by TheWaWaR** [comment]
There is a doc repo : https://github.com/NervJS/docs
You can read there for now.

**Comment by luckyadam** [comment]
Yeah,Now we only provide Chinese doc, the English version will come soon

**Comment by luckyadam** [comment]
@Maple13 CN document had been added

**Comment by Maple13** [comment]
I got it. Thanks for your reminding

**Comment by luckyadam** [comment]
@Maple13 You're welcome.Thank you for so much concern.
