### ISSUE TITLE
How does Nerv's server side rendering performance compare to React & Next.js?

### ISSUE THREAD

**Issue by selforganized** [NervJS/nerv#16]
Hi,

In Nerv's website there are a few benchmarks comparing its performance to that of React & a few other frameworks. Looks like those are all benchmarks for client-side rendering. 

What is Nerv's performance in server-side rendering? Especially when compared to React & Next.js? Any benchmarks available?

Thanks.

**Comment by yuche** [comment]
Here is a [isomorphic-ui-benchmarks](https://github.com/marko-js/isomorphic-ui-benchmarks) result, run by node v9.0.0, I will commit it to [benchmarks](https://github.com/NervJS/nerv/tree/master/benchmarks) soon:

```bash
Running "search-results"...

Running benchmark "marko"...

marko x 4,808 ops/sec ±1.33% (79 runs sampled)

Running benchmark "preact"...

preact x 744 ops/sec ±1.43% (85 runs sampled)

Running benchmark "react"...

react x 147 ops/sec ±1.83% (72 runs sampled)

Running benchmark "vue"...

vue x 1,538 ops/sec ±2.11% (73 runs sampled)

Running benchmark "inferno"...

inferno x 670 ops/sec ±1.31% (84 runs sampled)

Running benchmark "nerv"...

nerv x 943 ops/sec ±1.33% (87 runs sampled)

Fastest is marko

--------------


Warming up...

Warmup complete.

Running "color-picker"...

Running benchmark "marko"...

marko x 8,813 ops/sec ±1.37% (81 runs sampled)

Running benchmark "preact"...

preact x 4,119 ops/sec ±0.86% (85 runs sampled)

Running benchmark "react"...

react x 620 ops/sec ±2.02% (81 runs sampled)

Running benchmark "vue"...

vue x 4,445 ops/sec ±2.17% (73 runs sampled)

Running benchmark "inferno"...

inferno x 3,415 ops/sec ±1.28% (84 runs sampled)

Running benchmark "nerv"...

nerv x 5,138 ops/sec ±1.49% (84 runs sampled)

Fastest is marko

--------------


DONE!
✨  Done in 84.89s.
```

**Comment by Havunen** [comment]
Hey!

I have sent PR to isomorphic-benchmark to update the libraries, many of them are scoring better now. Inferno has also improved SSR up to 10 times. Here is link to PR: https://github.com/marko-js/isomorphic-ui-benchmarks/pull/10

**Comment by kurtextrem** [comment]
@Havunen I really don't want to sound rude, but wouldn't it make sense to work together on one big speedy alternative to React?
There are 3 major players as alternative now: 
- Preact, because it's the tiniest and probably most popular
- Inferno, speediest in SSR (after v4)
- Nerv, speediest in Client-Side
And Nerv is somewhat based on Inferno or it's principles, so why not merge those two?

**Comment by yuche** [comment]
@kurtextrem 
Inferno is fastest in Client-Side too, ahead of Nerv about 10% in js-framework-bench (both tested with latest stable). 

Although Nerv learn a lot from Inferno and preact, Nerv and Inferno is very different in the data structure, and the main goal: Nerv is more focus in React and browser compatibility, Inferno can more focus in performance. I don't think merge two of us is a really good idea.
