### ISSUE TITLE
Missing createFactory API

### ISSUE THREAD

**Issue by otakustay** [NervJS/nerv#17]
Although nervjs explicitly stated that `createFactory` is not supported currently, it is quite an important top level API which is required by [recompose](https://github.com/acdlite/recompose) which is further required  by many hoc libraries

**Comment by yuche** [comment]
Good to know.

recompose is one of my favorite library, so this feature definitely will be supported,

I will do it in couples days

**Comment by yuche** [comment]
`createFactory` is support from now. And `recompose` also works fine with me. 😄

**Comment by yuche** [comment]
Here is [basic example](https://github.com/yuche/nerv-recompose-example) that Nerv combine `recompose` and `styled-components `.

Closing the issue now. Have a good day~

**Comment by RXminuS** [comment]
I'm not sure this works 100% correct yet with `styled-components` I'm still trying to figure it out but ThemeProvider doesn't seem to be working correctly, somehow it's props are dropped. I'm trying to make an example repo to showcase the issue
