### ISSUE TITLE
Website appears broken

### ISSUE THREAD

**Issue by jhsware** [NervJS/nerv#18]
When visiting:

https://nerv.aotu.io/

with:

FF 57.0.3 (macOS High Sierra)
Chrome 63.0.3239.84 (macOS High Sierra)

Marker texts such as 'size_desc' where one would expect actual text to be present.

No errors in console.

If I click on the paging dot of the examples carousel I get:

```
ReferenceError: event is not defined
index.js:1:775917
t/e.switchCode      https://nerv.aotu.io/js/index.js:1:775917
onClick                   https://nerv.aotu.io/js/index.js:1:780157
e                             https://nerv.aotu.io/js/index.js:1:40029
i                              https://nerv.aotu.io/js/index.js:1:39903
```

**Comment by luckyadam** [comment]
Hello, it has been fixed. NervJS/nerv-website#1
Thank you!
