### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by styfle** [NervJS/nerv#20]
Typically there is a `CHANGELOG.md` in the root or [GitHub Releases](https://github.com/NervJS/nerv/releases) page is utilized to explain changes.

For example, what changed in version 1.2.3?

For comparison, see React which puts changes in both places:

- Change log: https://github.com/facebook/react/blob/master/CHANGELOG.md
- Releases: https://github.com/facebook/react/releases

**Comment by luckyadam** [comment]
Yeah,becourse of it's monorepo that we manage using Lerna,the CHANGELOG file was generated automatically.
https://github.com/NervJS/nerv/blob/master/packages/nerv/CHANGELOG.md
