### ISSUE TITLE
ReferenceError: global is not defined when trying to do server render

### ISSUE THREAD

**Issue by dzek69** [NervJS/nerv#24]
So I have a small preact application and I wanted to replace preact with `nerv`. After aliasing `react` and `react-dom` I replaced `render` import from `preact-render-to-string` to `nerv-server` and started bundled application (I am bundling server code as well, so my file loaders works as expected)... and the server crashed on this:

```javascript
const global = (function () {
    // the only reliable means to get the global object is
    // `Function('return this')()`
    // However, this causes CSP violations in Chrome apps.
    if (typeof self !== 'undefined') {
        return self;
    }
    if (typeof window !== 'undefined') {
        return window;
    }
    if (typeof global !== 'undefined') {
        return global;
    }
    throw new Error('unable to locate global object');
})();
```

with

```
if (typeof global !== 'undefined') {
    ^

ReferenceError: global is not defined
```

The code is from installed `nerv-server/dist/index.js`

I was surprised at first (crashing on `typeof`), but well, look at this:
```javascript
const a = (() => {
   console.log(typeof a)
})();
```

If you paste this into browser console it will always fail, because you're trying to get value of `a` while evaluating its value.

I have no idea how this can work anywhere and get to the "unable to locate ..." error, however I saw an closed Issue that was just about `unable to locale` being thrown.

Do you have any example repos with server-side rendering, so I can look closer how to do that properly. As my typical React/preact configuration seems not to work here.

**Comment by luckyadam** [comment]
Hello,please install `nervjs@beta` and `nerv-server@beta` to try again, this problem is resolved in the beta version.
So sorry to confuse you.

**Comment by dzek69** [comment]
No need to be sorry.

This fixed the `global` problem, some of my pages are server-rendered now, but some of them are crashing. I am gonna open separate issue for that.

Thank you for your help and good luck with `nerv`, definitely gonna watch this project :)
