### ISSUE TITLE
Server-side rendering is crashing with react-inform

### ISSUE THREAD

**Issue by dzek69** [NervJS/nerv#25]
I am using `1.2.4-beta.1`

When I am using `react-inform` and nerv-server - it crashes the render.

`state.values` seems to be `undefined`, so `values[name]` is crashing in this file: https://github.com/theadam/react-inform/blob/master/src/form.js

However when I render this in browser - everything is working as expected.

I'm not using anything fancy with `react-inform` so you should be able to reproduce this with basic example, but if not - I may try to isolate the issue out of my project and make a repo out of it.

**Comment by yuche** [comment]
That’s a really good catch.

`react-inform` is  calling `setState` in `componentWillMount`, In Nerv (and React) `setState` is a asynchronous function, so when the `component.render()` function is calling, `component.state` haven’t updated yet which cause crash.

The solution is simple: just clear the queueing state and merge them after `componentWillMount` was called during the server rendering.

Please re-install Nerv by running `npm install nervjs@beta` (1.2.5-beta.1) and try again.

**Comment by dzek69** [comment]
Thank for your reply, however the issue still persists.

**Comment by dzek69** [comment]
Hm, when installed by yarn - It wasn't there, but package.json version number was 1.2.5-beta.1 and resolved to: https://registry.yarnpkg.com/nerv-server/-/nerv-server-1.2.5-beta.1.tgz which should be a proxy for https://registry.npmjs.org/nerv-server/-/nerv-server-1.2.5-beta.1.tgz and I've manually downloaded it and it wasn't there.

I reinstalled deps using `npm` and it was there.

I cleaned yarn lock and node_modules and reinstalled with yarn and it resolved to 1.2.5-beta.2 and the change is there.

So I guess you've released wrong version and updated it in the meantime, right?

Anyway - this fixed the problem! :tada:

**Comment by yuche** [comment]
Just checking my `git log`
![image](https://user-images.githubusercontent.com/7202516/35001490-d3a24f48-fb21-11e7-8b54-d304bf78f73e.png)

I was published 1.2.5-beta.1 after fixing the bug. However, the change did not publish. 😂
Maybe I forget to build the file before publishing……

**Comment by dzek69** [comment]
add prepublishOnly hook :)
https://docs.npmjs.com/misc/scripts
