### ISSUE TITLE
新 diff 算法原理概述

### ISSUE THREAD

**Issue by yuche** [NervJS/nerv#3]
1. 找到相同的前置元素和后置元素

```
     *
     *  A: -> [a b c d] <-
     *  B: -> [a b d] <-
     *
```
这里我们可以发现前置元素 a, b 和 后置元素 d 都是相同的。所以我们可以将这样的 diff 情况转变为：
```

     *
     *  A: -> [c] <-
     *  B: -> [] <-
     *

```
这里我们可以发现 A 和 B 的不同就是多了一个 c 元素，所以只要进行把 c 元素移除这一步可以完成 diff。相反地，如果这步操作 A 为空，B 有多余元素，那么我们就将多余元素插入即可。
这一步 diff 优化最早由 [Neil Fraser](https://neil.fraser.name/writing/diff/) 提出，实现非常简单（在 Neil 的文章里他提供了 JavaScript，Java，Python 三种实现），优化的力度也非常大，但真正首次应用到前端框架却是十年后的 Bobril，后来号称性能最强的 Inferno 也使用了这一优化。

再来看下一种情况：
```

     *
     *  A: -> [a b c d e f g] <-
     *  B: -> [a c b h f e g] <-
     *

```
在这个情况的 diff 中，我们可以应用之前的优化策略把他简化为：

```
     *
     *  A: -> [b c d e f] <-
     *  B: -> [c b h f e] <-
     *
```

2. 这时候我们就需要进行第二步：找到需要被删除、插入或移动的元素：

首先我们创造一个数组 `P`，它代表新数组应该被插入的位置。

```
     *
     *  A: [b c d e f]
     *  B: [c b h f e]
     *  P: [. . . . .] // . == -1
     *
```

接下来我们再创建一个索引 `I`，作为新数组位置的映射（如果新旧数组都很小的话，那我们直接遍历数组即可，反之我们需要一个索引）：

```
     *
     *  A: [b c d e f]
     *  B: [c b h f e]
     *  P: [. . . . .] // . == -1
     *  I: {
     *    c: 0,
     *    b: 1,
     *    h: 2,
     *    f: 3,
     *    e: 4,
     *  }
     *  last = 0
     *
```

有了数组 `P` 和 索引 `I` 之后，现在我们可以开始遍历旧数组

```
 *
 *  A: [b c d e f]
 * 	^
 *  B: [c b h f e]
 *  P: [. 0 . . .] // . == -1
 *  I: {
 *    c: 0,
 *    b: 1, <-
 *    h: 2,
 *    f: 3,
 *    e: 4,
 *  }
 *  last = 1
 *
```
第一步遍历我们可以发现旧数组的 b 元素也在新数组上，所以我们把他在旧数组的位置 0 放到他在数组 P 相对应的位置上。

这里我们同时还要维护一个变量 last，它代表访问过的节点在旧集合中最右的位置(即最大的位置)。如果新集合中当前访问的节点比 last 大，说明当前访问节点在旧集合中就比上一个节点位置靠后，则该节点不会影响其他节点的位置，因此不必执行移动操作。只有当访问的节点比 last 小时，才需要进行移动操作。 

```
 *
 *  A: [b c d e f]
 * 	  ^
 *  B: [c b h f e]
 *  P: [1 0 . . .] // . == -1
 *  I: {
 *    c: 0, <-
 *    b: 1,
 *    h: 2,
 *    f: 3,
 *    e: 4,
 *  }
 *  last = 1 // last > 0; moved = true
 *
```

这里我们访问元素 c 的位置为 0，而 last 为 1，所以我们需要进行移动操作。

这一步实际上也是 React Stack Reconciler（React 16 以下）的核心算法：每次遍历的时候把当前节点在旧集合的位置和 last 进行对比，如果 mountIndex 大于 last，那么就把他添加到差异队列，然后更新 last，全部遍历完毕之后再遍历差异队列，一步一步进行 patch。

（这里如果理解有障碍的话建议把常规的排序算法都撸一遍，可以重点看选择排序和插入排序）

```
 *
 *  A: [b c d e f]
 *          ^
 *  B: [c b h f e]
 *  P: [1 0 . . .] // . == -1
 *  I: {
 *    c: 0,
 *    b: 1,
 *    h: 2,
 *    f: 3,
 *    e: 4,
 *  }
 *  moved = true
 *
```
这里元素 d 在新数组当中并不存在，所以它应该被移除掉。
```
 *
 *  A: [b c d e f]
 *            ^
 *  B: [c b h f e]
 *  P: [1 0 . . 3] // . == -1
 *  I: {
 *    c: 0,
 *    b: 1,
 *    h: 2,
 *    f: 3,
 *    e: 4, <-
 *  }
 *  moved = true
```

这里把元素 e 在旧数组的位置（3）放到数组 `P` 上。

```
 *
 *  A: [b c d e f]
 * 	        ^
 *  B: [c b h f e]
 *  P: [1 0 . 4 3] // . == -1
 *  I: {
 *    c: 0,
 *    b: 1,
 *    h: 2,
 *    f: 3, <-
 *    e: 4,
 *  }
 *  moved = true
 *
```
这里把元素 f 在旧数组的位置（4）放到数组 `P` 上。

到了这一步，如果是 React 的算法已经走完了。但不妨思考以下的 diff 情况：
```
 *
 * A: [a b c d]
 * B: [d a b c]
 *
```
这里肉眼一看就知道，把旧集合的 d 元素移动到 0 这一步操作就可以完成 diff。但根据前文所述的逻辑走一次，实际上 React 会先把 a, b, c 移动到他们的相应的位置 + 1，一共三步操作。

移动操作也并不是没有副作用，仍然可能会重启动画，focus 丢失，重置滚动条位置等。所以我们还可以进行下一步优化：

3. 找到最小的移动次数。

这里我们需要找到 `P` 数组的[最长递增子序列(longest increasing subsequence)] 来做动态规划，新集合中不属于这个序列的将会被移动。

还是用我们之前的例子：

```
 *
 *  A: [b c d e f]
 *  B: [c b h f e]
 *  P: [1 0 . 4 3] // . == -1
 *  LIS:     [1 4]
 *  moved = true
 *
```

这里我们同时尾部遍历新数组和 LIS 序列，查看元素的位置是否能与 LIS 序列的任何一个值匹配。

```
 *
 *  A: [b c d e f]
 *  B: [c b h f e]
 *              ^  // new_pos == 4
 *  P: [1 0 . 4 3] // . == -1
 *  LIS:     [1 4]
 *              ^  // new_pos == 4
 *  moved = true
 *
```
这一步能匹配，e 可以呆在它原来的位置上。

```
 *
 *  A: [b c d e f]
 *  B: [c b h f e]
 *            ^    // new_pos == 3
 *  P: [1 0 . 4 3] // . == -1
 *  LIS:     [1 4]
 *            ^    // new_pos != 1
 *  moved = true
 *
```

f 的位置不能匹配，把他移动到 e 之前。

```
 *
 *  A: [b c d e f]
 *  B: [c b h f e]
 *          ^      // new_pos == 2
 *  P: [1 0 . 4 3] // . == -1
 *          ^      // old_pos == -1
 *  LIS:     [1 4]
 *            ^
 *  moved = true
 *
```
h 的位置为 -1，把他插入。

```
 *
 *  A: [b c d e f]
 *  B: [c b h f e]
 *        ^        // new_pos == 1
 *  P: [1 0 . 4 3] // . == -1
 *  LIS:     [1 4]
 *            ^    // new_pos == 1
 *  moved = true
 *
```
b 能匹配 LIS，可以老老实实呆着。

```
 *
 *  A: [b c d e f]
 *  B: [c b h f e]
 *      ^          // new_pos == 0
 *  P: [1 0 . 4 3] // . == -1
 *  LIS:     [1 4]
 *          ^      // new_pos != undefined
 *  moved = true
 *
```
c 不能匹配，把它移动到 b 之前。

走完这一步我们的 diff 算法就完毕了。

这时回头再来看看之前把尾部元素插入到头部的情况，React 需要经过 3 次操作，而经过我们动态规划之后：
```
 *
 - A: [a b c d]
 - B: [d a b c]
 - P: [3 0 1 2]
 - LIS: [0 1 2]
 *
```
可以发现 b, c, d 能匹配 LIS，可以呆到天荒地老，我们只要把 d 移动到头部的位置就可以完成 diff。Perfect！

详细代码：
https://github.com/NervJS/nerv/blob/patch/packages/nerv/src/vdom/patch.ts

**Comment by zhangchen91** [comment]
可以发现 a,b, c, d 能匹配 LIS?

**Comment by yuche** [comment]
@zhangchen91 改了，谢谢。

**Comment by zhangchen91** [comment]
这个算法看了下，Inferno 也是这么实现的，可否认为建立『索引 I』是一种空间换时间的优化，让 LIS 算法变成 O(n)。
对了想问下之前几种编辑距离(Edit Distance)应该跟 LCS 是对偶问题吧，那么这种算法没办法优化到 O(n)么? 
编辑距离和最小移动应该算不同的问题吧？毕竟一个针对的是插删改，而后者针对的是移动？
最近为了看Diff算法补了好几篇论文有点头晕还没消化过来...

**Comment by yuche** [comment]
1.  是空间换时间。所以在具体的实现上会设置一个限制，当数组长度太低的时候就不建立索引了，直接遍历全部。大部分性能排行在 js-framwork-bench 前列的框架基本都是用这个算法，ivi 是最早使用的，其他的或多或少都参考了他。

2. 目前没发现可以优化到 O(n) 的算法，你给的链接应该是目前已经实现在 vdom 中最快的算法，期望复杂度是 O(n log n)。

3. 我个人认为是同一件事情，diff 算法的核心就是找最小的编辑距离，找最小移动只是其中的一个方法而已。

**Comment by zhangchen91** [comment]
了解，那之前好多文章写 React 的 Diff 算法复杂度是从 O(n^3) 优化到 O(n) 要如何理解呢？children 的这块就已经超越了 O(n) 了不是么？所以 O(n^3) 到 O(n) 的这个说法是不包含 children 的?

**Comment by kurtextrem** [comment]
I am sorry as I can't speak your language, but I am still interested in this topic, would someone please be so kind to translate it to me? (Google Translator doesn't really work well)

**Comment by yuche** [comment]
我猜这类文章指的是整棵树的对比是 O(n ^ 3)，而 React 只对比同级元素，并且他们的 `type` 和 `key` 是一致才继续 diff (包括他们 children)下去，否则就直接替换或删除掉。从这个意义上来讲，这些文章也没有讲错。

**Comment by yuche** [comment]
@kurtextrem 
Check this out:
https://github.com/adamhaile/surplus/blob/5f5ad8d9e7eb6db954cd146bd48772f77886b295/es/content.js
https://github.com/ivijs/ivi/blob/2c81ead934b9128e092cc2a5ef2d3cabc73cb5dd/packages/ivi/src/vdom/implementation.ts#L12:81

**Comment by gu18168** [comment]
请问，为何最后一步是尾部遍历新数组 B 呢？明明 P 中存储的是元素在旧数组 A 中的位置。而且如果是遍历新数组的话，尾部元素插入到头部中的 a, b, c 为什么能匹配 LIS，明明他们的新位置是 1, 2, 3 ？
时间隔了很久才发现这篇文章，现在提问打扰了。

**Comment by WzFFzW** [comment]
请问一下，找到LIS之后，可不可以换成这样
1.  找到LIS
2. 正序遍历新数组，从P中得到元素对应的位置
3. 判断元素所在的位置是不是在LIS中
4. 如果是，就不移动当前元素，如果不是，就移动当前元素到对应位置。
不知道这样和你的思路是否一样，（因为我没看代码，所以不清楚你的代码是不是这样的思路）

**Comment by oychao** [comment]
@WzFFzW 第4步有问题，不是移动当前元素到对应位置，而是插入当前元素到last元素的后面，last代表访问过的节点在新集合中最左的位置。

**Comment by triboby** [comment]
```
 *
 *  A: [b c d e f]
 *            ^
 *  B: [c b h f e]
 *  P: [1 0 . . 3] // . == -1
 *  I: {
 *    c: 0,
 *    b: 1,
 *    h: 2,
 *    f: 3,
 *    e: 4, <-
 *  }
 *  moved = true
```
e这步的moved是false ？

**Comment by wizardpisces** [comment]
> ```
>  *
>  *  A: [b c d e f]
>  *            ^
>  *  B: [c b h f e]
>  *  P: [1 0 . . 3] // . == -1
>  *  I: {
>  *    c: 0,
>  *    b: 1,
>  *    h: 2,
>  *    f: 3,
>  *    e: 4, <-
>  *  }
>  *  moved = true
> ```
> 
> e这步的moved是false ？

按照他的表述确实应该是 false，但是通篇看下来并没发现moved的作用，主要就是通过新旧数组来生成那个变化数组
