### ISSUE TITLE
您好，请问可以提供一个能够在 IE8 下使用的 DEMO 吗？

### ISSUE THREAD

**Issue by BiosSun** [NervJS/nerv#36]
因为我参照了很多的资料，但总是无法配置出一个能够在 IE8 下使用的 DEMO。

**Comment by yuche** [comment]
这个 repo 的测试就能在 IE8 上跑，你可以参考一下。

**Comment by yuche** [comment]
主要看 [karma.config.js](https://github.com/NervJS/nerv/blob/master/karma.conf.js) 的 webpack 部分 和 babelrc
