### ISSUE TITLE
做了个简单demo，nerv+nextjs跑不起来

### ISSUE THREAD

**Issue by lolipop99** [NervJS/nerv#37]
```javascript
//.babelrc配置
"plugins": [
    [
      "transform-react-jsx",
      {
        "pragma": "Nerv.createElement"
      }
    ],
    [
      "module-resolver", 
      {
      "root": ["."],
      "alias": {
          "react": "nervjs",
          "react-dom": "nervjs",
          "create-react-class": "nerv-create-class"
      }
    }]
  ]

// page/index.js
import React from 'react'

export default () => <div>Welcome to next.js!</div>
```
![1516986826288](https://user-images.githubusercontent.com/6138899/35451792-5c1c5686-02ff-11e8-872e-e9f479d6b9fc.jpg)

**Comment by yuche** [comment]
Next.js 的设置应该是在根目录的 `next.config.js`: 

```js
module.exports = {
  webpack: function (config) {
    config.resolve.alias = {
      'react': 'nervjs',
      'react-dom': 'nervjs'
    }

    return config
  }
}

```

可以看这个例子：
https://github.com/zeit/next.js/tree/9320d9f006164f2e997982ce76e80122049ccb3c/examples/using-preact

**Comment by lolipop99** [comment]
@yuche 大佬

用nerv-server包，是无法做到同构的吧。

我这边根据文档编译出来的只是单纯的html字符串，这样说nerv-server包定位只是做内容直出，数据获取这些需要引入其它解决方案？

**Comment by yuche** [comment]
简单来说 `nerv-server` 和 `react-dom/server` 没什么两样（除了目前暂不支持 stream），如果你能渲染字符串，配合 `hydrate` 就可以做服务端渲染了。
Next.js 或者阿里的 beidou 都是包了一层 webpack/语法糖/css 处理而已。

可以参考这篇文章：
http://www.alloyteam.com/2017/01/react-from-scratch-server-render/

**Comment by lolipop99** [comment]
好的 谢谢大佬。

我再好好深入深入下。

**Comment by lipp** [comment]
hi there @yuche @lolipop99! i was trying the run the "using-nerv" example of next.js. I was guessing this issue might be related to it. Could you be so kind and tell me what the essence of this issue is?
Thank you very much! 

I created an issue on on the next.js issue page https://github.com/zeit/next.js/issues/3868
