### ISSUE TITLE
found radium doesn't work in nerv?

### ISSUE THREAD

**Issue by ranglang** [NervJS/nerv#39]
the link for radium https://github.com/FormidableLabs/radium.
i will show a sanbox later

**Comment by ranglang** [comment]
a snippet cound be found  in https://github.com/ranglang/bug-check-radium-in-nervjs/blob/master/main1.jsx

```
   render() {
        return (
            <div id="app" style={[styles.warning, styles.primary]}>
                <h1>h1</h1>
            </div>
        )
    }
}

const Enhanced = Radium(App)
```
### result
children of dom  (id=app) should be show.


![](http://dn-lqiong.qbox.me/Screenshot%20from%202018-02-07%2010-14-10.png)

**Comment by yuche** [comment]
The problem might have been fixed. Please install latest version(1.2.11) and try again.
