### ISSUE TITLE
unkeyed children diffing error causes component lifecycle event to fire unexpectedly

### ISSUE THREAD

**Issue by yaodingyd** [NervJS/nerv#40]
[test case](https://codesandbox.io/s/0pr0m5lmlv)

Click two buttons 
Expected: console log should only has "updated"
Results: Console log gets "mounted" and "unmounted". 

 Basically, if parent component B has unkeyed children, and there are children add/remove before child component A,  even though the changed child is not a component A, A still gets mounted/unmounted, because unkeyed children are diffed in sequential order.

In the Inferno way, it has normalized VNode so if key is not set, it might use children order and `null` is considered a child too, so child component  always has the same normalized key, thus gets the correct diffing results.

**Comment by yuche** [comment]
Thanks for reporting this issue.
Your test case can be found in:  https://github.com/NervJS/nerv/blob/218563a285dd81b853ac62c86fe850ae9355f12a/packages/nerv/__tests__/patch.spec.js#L129-L206
