### ISSUE TITLE
Adds node instead of replacing

### ISSUE THREAD

**Issue by kurtextrem** [NervJS/nerv#42]
I found a weird bug and I'm not sure what the cause is.

I have the following code:
```jsx
<div id="app">
	<Header location={this.state.location} />
	<main className="d-flex justify-content-center">
		<HashRouter onLocationChanged={this.handleLocationChanged}>
			<Route key="liked" hash="#/">
				<Liked />
			</Route>
			<Route key="saved" hash="#/saved">
				<Saved />
			</Route>
			<Route key="about" hash="#/about">
				<About />
			</Route>
		</HashRouter>
	</main>
</div>
```

`HashRouter` render function:
```jsx
return this.state.render
```

In the state, only one child is saved (double checked with console.log and dev tools). However, when I render a different component (so to say, a route change is happening), this happens:
![screenshot_6](https://user-images.githubusercontent.com/502146/36340752-42490e80-13e3-11e8-966f-998bc7410d14.png)

So it seems Nerv is adding the component/a Node to the DOM instead of replacing it. Both  `<Liked />` and `<About />` render a `<div>`, the latter one with `className="..."`.

Code is here: https://github.com/kurtextrem/Improved-for-Instagram/blob/master/src/components/HashRouter.js#L152 / https://github.com/kurtextrem/Improved-for-Instagram/blob/master/src/components/app.js#L44

**Comment by kurtextrem** [comment]
So I investigated and it seems to be because of this:
![screenshot_10](https://user-images.githubusercontent.com/502146/36342671-f44c0f06-1401-11e8-9110-05bbb86202b0.png)

However, I don't know why the `dom` prop is a Text node.

**Comment by kurtextrem** [comment]
If I replace `PostsContainer`'s `return null` with `return <span />` (or with `<div />` simply nothing happens. The new component is not rendered (it is not even added to the DOM).
So currently I'm investigating why the `dom` prop refers to a Node that is out of the DOM already.

**Comment by kurtextrem** [comment]
The faulty line is definitely in `mountComponent()`, to be specific `var dom = vnode.dom = component.dom = mountVNode(rendered, getChildContext(component, parentContext), component);`

So the issue is, `.dom` does not get updated to the new content. But why? I have no idea.

**Comment by yuche** [comment]
Try: 
```js
# HashRouter.js
export const Route = props => <div>{props.children}</div>
```

**Comment by kurtextrem** [comment]
Works great!
So just wondering, why is the div needed?

**Comment by yuche** [comment]
Your code is solid, the original way should also works fine,  but Nerv lost the component's DOM reference during the diff/patch algorithm in some case.
It's a little bit tricky to fix, hopefully we can release a minor patch in a day or two.

PS:
You should deal with filename case sensitivity problem in `Improved-for-Instagram` project. It's important in EXT4 file system.

**Comment by kurtextrem** [comment]
Thank you!

> You should deal with filename case sensitivity problem in Improved-for-Instagram project. It's important in EXT4 file system.

I've noticed this too. However, I'm not sure how I can tell GitHub to do that. On my local system, all components are starting with an uppercase letter. On GitHub they aren't.

**Comment by chuyik** [comment]
@kurtextrem You may want to use command like 
`git mv -f app.js App.js` 
to rename the files with case-sensitive issue.

**Comment by yuche** [comment]
I have been pull a new request in your project. It works file in my computer.
But IMHO, the better way is change all filename to upper camel case.

**Comment by kurtextrem** [comment]
Thank you!!! 🎉

**Comment by yuche** [comment]
Please install the beta version with `npm i --save nervjs@beta` , drop the `div` wrapper and retry.
The beta version may fixed the devtools problem as well.

**Comment by kurtextrem** [comment]
Hm, I've updated to the latest nervjs, but when I remove the `div` wrapper it does not update. When I add it back again, it does update.

**Comment by yuche** [comment]
It’s beta version, not the latest. The correct version should be 1.2.14-beta-0.

Regards,

Che Yu

2018年3月2日 +0800 PM8:11 Jacob Groß <notifications@github.com>，写道：
