### ISSUE TITLE
nerv-devtools error!!!

### ISSUE THREAD

**Issue by PedroGao** [NervJS/nerv#47]
nerv-devtools  always works well ，but when add the react-router-dom  ， it is error !   

> TypeError: Cannot read property 'type' of null
createReactDOMComponent
E:/demos/ReactApp/nerv-app/node_modules/nerv-devtools/dist/index.esm.js:74

>  71 | _currentElement: isText
  72 |     ? vnode.text
  73 |     : {
> 74 |         type: vnode.type,
  75 |         props: normalizeProps(vnode.props)
  76 |     },
  77 | _renderedChildren: normalizeChildren(vnode.children),

**Comment by yuche** [comment]
What's your `reaact-router-dom` version?

**Comment by PedroGao** [comment]
"react-router-dom": "^4.2.2"  
which version could i choose?

**Comment by yuche** [comment]
Try install beta version with `npm i  nervjs@beta` and retry.

**Comment by PedroGao** [comment]
> backend.js:8901 Uncaught TypeError: Cannot read property 'displayName' of undefined
    at getDisplayName (backend.js:8901)
    at getData (backend.js:8743)
    at walkNode (backend.js:8576)
    at backend.js:8579
    at Array.forEach (<anonymous>)
    at walkNode (backend.js:8578)
    at backend.js:8579

it failed.

**Comment by yuche** [comment]
Where is the `getDisplayName` function come from?

**Comment by PedroGao** [comment]
It is in the React Deveplope Tools . 
And the breakpoint is here
``` js
         // The displayName property is not guaranteed to be a string.
	  // It's only safe to use for our purposes if it's a string.
	  // github.com/facebook/react-devtools/issues/803
	  if (typeof type.displayName === 'string') {
	    displayName = type.displayName;
	  }
```

**Comment by PedroGao** [comment]
Now it's working.

**Comment by iuliaL** [comment]
Same issue here
Not using any react lib though
<img width="568" alt="screen shot 2018-04-10 at 12 07 49" src="https://user-images.githubusercontent.com/15954865/38547510-e3c30c00-3cb7-11e8-89a9-91dcf51f143e.png">

**Comment by iuliaL** [comment]
After upgrading to nervjs@beta i get another error
> index.esm.js?a32c:2083 Uncaught (in promise) TypeError: Cannot read property 'dom' of undefined
    at Object.findDOMNode (index.esm.js?a32c:2083)
    at getContainer (Portal.js?7f9e:155)
    at Portal._mountOverlayTarget (Portal.js?7f9e:120)
    at Portal._renderOverlay (Portal.js?7f9e:100)
    at Portal.componentDidMount (Portal.js?7f9e:41)
    at eval (index.esm.js?a32c:1550)
    at errorCatcher (index.esm.js?a32c:1456)
    at eval (index.esm.js?a32c:1549)
    at Array.forEach (<anonymous>)
    at flushMount (index.esm.js?a32c:1545)

**Comment by kurtextrem** [comment]
@iuliaL nervjs@beta actually contains an older release than `nervjs@latest`
