### ISSUE TITLE
将 React 切换为 Nerv 后，在 Ant Design 有些组件报错！

### ISSUE THREAD

**Issue by nuintun** [NervJS/nerv#59]
如题，切换后一些组件，例如 ```Table``` ， ```Tabs``` 报错，而 ```Checkbox```  等一些组件是可以的！

![tim 20180404221359](https://user-images.githubusercontent.com/1730277/38312936-88a3b6e6-3855-11e8-8c5c-5bcf44570702.png)

![tim 20180404221158](https://user-images.githubusercontent.com/1730277/38312939-8a835f7a-3855-11e8-8c41-0feb8acbd94c.png)

![tim 20180404221242](https://user-images.githubusercontent.com/1730277/38312944-8c1273bc-3855-11e8-9730-c77c29b88bce.png)

难道是姿势不对 ，有木有 ```DEMO``` 😂

**Comment by dai875939260** [comment]
感觉很难啊，antd编译出来的代码就不兼容ie8,比如这段就不兼容，typeof在ie8下不正常
```
if ("function" != typeof t && null !== t)
            throw new TypeError("Super expression must either be null or a function, not " + (void 0 === t ? "undefined" : (0, s["default"])(t)));
```

**Comment by luanwulin** [comment]
antd 官方说过的，要支持ie8就只能用1.X 的版本

**Comment by 23hp** [comment]
跟哪套UI库的兼容比较好呢。自己写UI库得花不少功夫啊   
Which UI libray should I use? It would cost too much to write one by self .
