### ISSUE TITLE
react-reconciler: Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by drcmda** [NervJS/nerv#6]
It seems to have trouble working together with react-reconciler:

<img width="1240" alt="screen shot 2018-01-10 at 20 33 10" src="https://user-images.githubusercontent.com/2223602/34791521-8642577e-f645-11e7-8f19-754542a5fa94.png">
<img width="1024" alt="screen shot 2018-01-10 at 20 33 00" src="https://user-images.githubusercontent.com/2223602/34791528-88f7b6ee-f645-11e7-9d2f-8b3d1f5cadef.png">

Is ReactInternals.ReactCurrentOwner something that nerv should fill out or is it a random internal?

**Comment by luckyadam** [comment]
Thanks, we will soon resolve this problem!

**Comment by yuche** [comment]
Sorry, you can't use `react-reconciler `  in Nerv since Nerv implement own diff algo.
