### ISSUE TITLE
关于对ie8下面 onpropertyChangeEvent全局性处理的疑问

### ISSUE THREAD

**Issue by coffeehc** [NervJS/nerv#60]
先贴下代码:
https://github.com/NervJS/nerv/blob/8d74124d87c5c429e0f159992cb9c4baa9ffba2c/packages/nerv/src/event.ts#L189-L203

1. 为什么190行需要把单个input的onchange事件绑定到一个全局的propertyChangeActiveHandler上面去?
2. 191-192行 ,为什么用bindFocus这个变量让onchange事件只能绑定一次,这个样在一个表单里面,有多个input的时候,只有一个input的onchange是生效的.

不太明白为什么要做这个样的处理,这个明显会导致form在ie8下面失效,想不明白,
望解答

**Comment by yuche** [comment]
close via #61 .
