### ISSUE TITLE
NGE? Could it be?

### ISSUE THREAD

**Issue by Onumis** [NervJS/nerv#7]
I came hoping for this

http://evangelion.wikia.com/wiki/NERV

![giphy-downsized](https://user-images.githubusercontent.com/1113178/34792614-5e0e8eb2-f627-11e7-94af-66009a6d1774.gif)

and now I am 

![giphy-downsized](https://media.giphy.com/media/3oAt21Fnr4i54uK8vK/giphy.gif)

**Comment by luckyadam** [comment]
Alllo, young man. I'm Ikari Gendou.Welcome to NERV.
