### ISSUE TITLE
为什么npm run dev IE8下报错，build后又显示正常

### ISSUE THREAD

**Issue by wenfung** [NervJS/nerv#70]

**Comment by lee1hang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
走webpack的话应该都是这样吧，webpack的原因。可以配个build watch然后开个anywhere试试


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                                    



    在2018年05月10日 20:36，wenfung<notifications@github.com> 写道：
