### ISSUE TITLE
实际render结果和state不一致（有codesandbox的demo）

### ISSUE THREAD

**Issue by wen911119** [NervJS/nerv#88]
Reproduction link
[https://codesandbox.io/s/qlpj0071qw](https://codesandbox.io/s/qlpj0071qw)
Steps to reproduce
1.在手机或者Chrome手机模拟器打开测试页面
2.下拉页面，并松手

期望结果：
页面弹回
实际结果：
页面没有弹回

补充信息：
控制台打印出了对后一次render时候的style，对比实际dom上的style，不一致。

用react创建了一个一样的demo是正常的：
[https://codesandbox.io/s/kx1ox76y5o](https://codesandbox.io/s/kx1ox76y5o)

**Comment by wen911119** [comment]
1.3.3 [试了下，还是不行。](https://codesandbox.io/s/qlpj0071qw) @yuche

**Comment by yuche** [comment]
兄弟，一件非常尴尬的事情，我发 1.3.3 的时候忘了 build。。

**Comment by wen911119** [comment]
。。。坐等1.3.4

**Comment by wen911119** [comment]
可以了，非常感谢！
